# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
r: bioc-release
sudo: false
cache: packages
warnings_are_errors: false
bioc_required: true